name: Android CI

on:
  pull_request:
  push:
    branches:
    - 'main'
    - '7.**'
    - 'feature/tap-to-record'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v5

    - name: Build with Gradle
      run: ./gradlew :Signal-Android:assemblePlayProdDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: signal-tap-to-record-debug
        path: app/build/outputs/apk/playProd/debug/app-play-prod-debug.apk

    - name: Archive reports for failed build
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: '*/build/reports'
